# Generated by Django 5.1.15 on 2026-10-04 17:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CycleReport',
            fields=[
                ('cycle_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField()),
                ('session', models.CharField(max_length=32)),
                ('received_at', models.DateTimeField()),
                ('raw_payload', models.JSONField()),
            ],
            options={
                'db_table': 'cycle_reports',
            },
        ),
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('gateway_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('token', models.CharField(default=uuid.uuid4, max_length=128, unique=True)),
                ('status', models.CharField(choices=[('new', 'new'), ('spare', 'spare'), ('connected', 'connected'), ('stale', 'stale'), ('disconnected', 'disconnected'), ('suspended', 'suspended'), ('retired', 'retired')], default='new', max_length=32)),
                ('status_since', models.DateTimeField()),
                ('command_state', models.CharField(choices=[('running', 'running'), ('stop_pending', 'stop_pending'), ('stopped', 'stopped'), ('stop_failed', 'stop_failed'), ('resume_pending', 'resume_pending'), ('resume_failed', 'resume_failed')], default='running', max_length=32)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('last_qualifying_at', models.DateTimeField(blank=True, null=True)),
                ('disconnected_since', models.DateTimeField(blank=True, null=True)),
                ('command_seq', models.IntegerField(default=0)),
                ('stop_period_acked_at', models.DateTimeField(blank=True, null=True)),
                ('resume_period_acked_at', models.DateTimeField(blank=True, null=True)),
                ('has_collecting_after_stop', models.BooleanField(default=False)),
                ('suspend_reason', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gateways',
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('sensor_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=64)),
                ('lifecycle', models.CharField(choices=[('pending', 'pending'), ('active', 'active'), ('dormant', 'dormant'), ('sampling', 'sampling'), ('retired', 'retired'), ('decommissioned', 'decommissioned')], default='pending', max_length=32)),
                ('lifecycle_reason', models.CharField(blank=True, max_length=256, null=True)),
                ('lifecycle_since', models.DateTimeField()),
                ('quiet_checked_days', models.IntegerField(default=0)),
                ('sampling_cycles_done', models.IntegerField(default=0)),
                ('wait_window_started_at', models.DateTimeField(blank=True, null=True)),
                ('available_seconds_accumulated', models.FloatField(default=0.0)),
                ('last_coverage_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_reading_taken_at', models.DateTimeField(blank=True, null=True)),
                ('next_evaluation_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sensors',
            },
        ),
        migrations.CreateModel(
            name='SystemState',
            fields=[
                ('singleton_id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('virtual_clock', models.DateTimeField(blank=True, null=True)),
                ('processing_failures_remaining', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'system_state',
            },
        ),
        migrations.CreateModel(
            name='CycleResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.CharField(max_length=128)),
                ('outcome', models.CharField(max_length=32)),
                ('batch_id', models.CharField(blank=True, max_length=128, null=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='monitor.cyclereport')),
            ],
            options={
                'db_table': 'cycle_results',
            },
        ),
        migrations.AddField(
            model_name='cyclereport',
            name='gateway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to='monitor.gateway'),
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('command_id', models.CharField(default=uuid.uuid4, max_length=128, primary_key=True, serialize=False)),
                ('seq', models.IntegerField()),
                ('type', models.CharField(choices=[('stop', 'stop'), ('resume', 'resume')], max_length=16)),
                ('issued_at', models.DateTimeField()),
                ('acked_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='monitor.gateway')),
            ],
            options={
                'db_table': 'commands',
                'ordering': ['seq'],
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('batch_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('sensor_id_raw', models.CharField(max_length=128)),
                ('received_at', models.DateTimeField()),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processing', models.CharField(choices=[('received', 'received'), ('processed', 'processed'), ('partially_processed', 'partially_processed'), ('retrying', 'retrying'), ('quarantined', 'quarantined')], default='received', max_length=32)),
                ('attempts', models.IntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_count', models.IntegerField(default=0)),
                ('quarantined', models.JSONField(default=list)),
                ('quarantine_reason', models.CharField(blank=True, max_length=128, null=True)),
                ('raw_payload', models.JSONField()),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='monitor.gateway')),
                ('sensor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='monitor.sensor')),
            ],
            options={
                'db_table': 'batches',
            },
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('reading_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('taken_at', models.DateTimeField()),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=32)),
                ('accepted', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='monitor.batch')),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='monitor.gateway')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='monitor.sensor')),
            ],
            options={
                'db_table': 'readings',
            },
        ),
        migrations.CreateModel(
            name='TimelineEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField()),
                ('kind', models.CharField(choices=[('transition', 'transition'), ('correction', 'correction'), ('action', 'action'), ('ack', 'ack'), ('flag', 'flag'), ('rule_change', 'rule_change')], max_length=32)),
                ('axis', models.CharField(max_length=32)),
                ('from_state', models.CharField(blank=True, db_column='from_state', max_length=128, null=True)),
                ('to_state', models.CharField(blank=True, db_column='to_state', max_length=128, null=True)),
                ('effective_at', models.DateTimeField()),
                ('recorded_at', models.DateTimeField()),
                ('rule', models.CharField(blank=True, max_length=256, null=True)),
                ('evidence_ids', models.JSONField(default=list)),
                ('gateway', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeline_entries', to='monitor.gateway')),
                ('sensor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeline_entries', to='monitor.sensor')),
            ],
            options={
                'db_table': 'timeline_entries',
                'ordering': ['seq'],
            },
        ),
        migrations.CreateModel(
            name='GatewaySensorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField()),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_assignments', to='monitor.gateway')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gateway_assignments', to='monitor.sensor')),
            ],
            options={
                'db_table': 'gateway_sensor_assignments',
                'unique_together': {('gateway', 'sensor')},
            },
        ),
    ]
